### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by mhayen** [WildH0g/apps-script-engine-template#2]
Hi Dmitry, 
I submitted a PR with some small improvements I hope at least.
[This one](https://github.com/WildH0g/apps-script-engine-template/pull/1)

Please give me you feedback.

Mark

**Comment by WildH0g** [comment]
Hi Mark, 

Thanks for your interest and contributions! I've left come comments in the code review. Going forward, please do the following:

1. Open an issue **before** making a pull request, this will save us a lot of time and effort :)
2. Make your PRs smaller please. You have multiple changes here, they need to be atomic (getting started is one PR, `.gitignore` is another one ... they are different features and don't belong together).

**Comment by WildH0g** [comment]
@mhayen Hey Mark, haven't heard from you in a while, do you intend to continue with the PR? Let me know.

**Comment by WildH0g** [comment]
No feedback for moths, closing this issue and the PR
